### ISSUE TITLE
1. Wczytywanie korpusu z .zip + przetwarzanie korpusu (tagowanie) + baza danych

### ISSUE THREAD

**Issue by 3bicik** [MichalSurmacki/slowik-api#2]

**Comment by MichalSurmacki** [comment]
Tablica haszująca, gdzie klucz to lemat a wartość to lista numerów zdań w korpusie w, których znajduje się zadane słowo.
Przetwarzanie korpusu będzie się odbywało za pomocą XML Serializatora (sprawdzić czy można utworzyć w.w. tablice haszującą podczas deserializacji).
Serializator będzie parsował CCL'a na obiekty (bez zapisywania w bazie).
CCL będzie zapisywany w bazie.
